### ISSUE TITLE
No progress being shown

### ISSUE THREAD

**Issue by za** [padok-team/yatas#111]
Hi there,

After I run `yatas` I can't see the progress being shown, unlike [the animated picture](https://github.com/padok-team/yatas/blob/main/docs/demo.gif) written on README. However, I can see the scan results.

I just wondering, without progress status, I am not sure whether yatas is running properly or not.

**Comment by za** [comment]
cc: @StanGirard

**Comment by za** [comment]
Hi @StanGirard just in case you miss the notification. Not urgent though.

**Comment by corrieriluca** [comment]
Hello @za,

Thank you very much for using YATAS!

The progress bar is unfortunately not available anymore. Since the beginning of the project, YATAS has been rewritten with the plugin architecture it has today (with a plugin for [AWS](https://github.com/padok-team/yatas-aws) as well as for [GCP](https://github.com/padok-team/yatas-gcp)) and one of the caveats of this approach is that YATAS (the main program) only waits results from the plugin and has no information about the progress, so there is no progress bar anymore 😕 

If you have an idea on how to implement it, do not hesitate to contribute! 😉

**Comment by za** [comment]
Hi @corrieriluca thanks for the info. I thought: mine was not working fine. I've no idea at the moment, so I'll close this issue then.
